/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_v1_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Account */
        delete: operations["delete_account_api_v1_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Calendars */
        get: operations["discover_calendars_api_v1_accounts__account_id__calendars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect Account */
        post: operations["disconnect_account_api_v1_accounts__account_id__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{account_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Account Access */
        post: operations["verify_account_access_api_v1_accounts__account_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activity */
        get: operations["list_activity_api_v1_audit_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Entry */
        get: operations["get_activity_entry_api_v1_audit_entries__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-entries/{entry_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Entry Changes */
        get: operations["get_activity_entry_changes_api_v1_audit_entries__entry_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-entries/{entry_id}/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Activity Event */
        get: operations["inspect_activity_event_api_v1_audit_entries__entry_id__event_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/google/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Configuration */
        get: operations["google_configuration_api_v1_google_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/oauth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google Oauth */
        get: operations["start_google_oauth_api_v1_oauth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recent-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Changes */
        get: operations["recent_changes_api_v1_recent_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        /** Create Rule */
        post: operations["create_rule_api_v1_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule Details */
        get: operations["rule_details_api_v1_rules__rule_id__get"];
        put?: never;
        post?: never;
        /** Remove Rule */
        delete: operations["remove_rule_api_v1_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /** Change Rule Policy */
        patch: operations["change_rule_policy_api_v1_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Rule */
        post: operations["enable_rule_api_v1_rules__rule_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Rule */
        post: operations["pause_rule_api_v1_rules__rule_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Rule */
        post: operations["preview_rule_api_v1_rules__rule_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Now */
        post: operations["reconcile_now_api_v1_rules__rule_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace Rule Calendars */
        post: operations["replace_rule_calendars_api_v1_rules__rule_id__replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Now */
        post: operations["sync_now_api_v1_rules__rule_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Status */
        get: operations["session_status_api_v1_session_get"];
        put?: never;
        /** Log In */
        post: operations["log_in_api_v1_session_post"];
        /** Log Out */
        delete: operations["log_out_api_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Admin */
        post: operations["create_admin_api_v1_setup_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage Usage */
        get: operations["storage_usage_api_v1_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clearable Activity */
        get: operations["clearable_activity_api_v1_storage_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/activity/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Activity */
        post: operations["clear_activity_api_v1_storage_activity_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Logs */
        get: operations["download_logs_api_v1_storage_logs_get"];
        put?: never;
        post?: never;
        /** Purge Logs */
        delete: operations["purge_logs_api_v1_storage_logs_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEventResponse */
        ActivityEventResponse: {
            destination: components["schemas"]["EventSnapshotResponse"] | null;
            source: components["schemas"]["EventSnapshotResponse"];
        };
        /** AuditEntryResponse */
        AuditEntryResponse: {
            /** Action */
            action: string;
            /**
             * Category
             * @enum {string}
             */
            category: "changed" | "unchanged" | "skipped" | "blocked";
            /** Changed Fields */
            changed_fields: string[] | null;
            /** Destination Event Id */
            destination_event_id: string | null;
            /** Detail */
            detail: string;
            event: components["schemas"]["RecordedEventResponse"] | null;
            /** Id */
            id: number;
            /** Occurred At */
            occurred_at: string;
            /** Outcome */
            outcome: string;
            /** Reason */
            reason: string | null;
            /**
             * Repeated
             * @default false
             */
            repeated: boolean;
            /** Rule Id */
            rule_id: string;
            /** Run Id */
            run_id: string | null;
            /** Source Event Id */
            source_event_id: string | null;
        };
        /** CalendarEndpointPayload */
        CalendarEndpointPayload: {
            /** Calendar Id */
            calendar_id: string;
            /** Connected Account Id */
            connected_account_id: string;
        };
        /** ClearActivityRequest */
        ClearActivityRequest: {
            /** Older Than Days */
            older_than_days: number;
        };
        /** ClearableActivityResponse */
        ClearableActivityResponse: {
            /** Entries */
            entries: number;
            /** Older Than Days */
            older_than_days: number;
        };
        /** ClearedActivityResponse */
        ClearedActivityResponse: {
            database: components["schemas"]["DatabaseUsageResponse"];
            /** Removed */
            removed: number;
        };
        /** ConnectedAccountResponse */
        ConnectedAccountResponse: {
            /** Authorized At */
            authorized_at: string | null;
            /** Avatar Url */
            avatar_url: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Rule Count */
            rule_count: number;
            /** State */
            state: string;
        };
        /** CreateRuleRequest */
        CreateRuleRequest: {
            destination: components["schemas"]["CalendarEndpointPayload"];
            /**
             * Privacy Policy
             * @default busy_only
             * @enum {string}
             */
            privacy_policy: "busy_only" | "copy_details";
            source: components["schemas"]["CalendarEndpointPayload"];
            /**
             * Sync All Day Events
             * @default true
             */
            sync_all_day_events: boolean;
            /**
             * Tentative Events
             * @default mark
             * @enum {string}
             */
            tentative_events: "sync" | "mark" | "skip";
            /**
             * Unanswered Invitations
             * @default as_tentative
             * @enum {string}
             */
            unanswered_invitations: "wait" | "as_tentative";
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Blocked Entry Id */
            blocked_entry_id: number | null;
            /**
             * Blocked Events
             * @default 0
             */
            blocked_events: number;
            /** Blocked Rule Id */
            blocked_rule_id: string | null;
            /** Connected Accounts */
            connected_accounts: number;
            /** Disconnected Accounts */
            disconnected_accounts: number;
            /** Enabled Rules */
            enabled_rules: number;
            /**
             * Health
             * @enum {string}
             */
            health: "healthy" | "attention";
            /** Last Synced At */
            last_synced_at: string | null;
            /** Open Incidents */
            open_incidents: number;
            /** Stopped Rules */
            stopped_rules: number;
            /** Sync Rules */
            sync_rules: number;
        };
        /** DatabaseUsageResponse */
        DatabaseUsageResponse: {
            /** Activity Entries */
            activity_entries: number;
            /** Bytes */
            bytes: number;
            /** Oldest Activity At */
            oldest_activity_at: string | null;
            /** Reclaimable Bytes */
            reclaimable_bytes: number;
        };
        /** DiscoveredCalendarResponse */
        DiscoveredCalendarResponse: {
            /** Access Role */
            access_role: string;
            /** Id */
            id: string;
            /** Primary */
            primary: boolean;
            /** Summary */
            summary: string;
            /** Writable */
            writable: boolean;
        };
        /** DriftResponse */
        DriftResponse: {
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
        };
        /** EventSnapshotResponse */
        EventSnapshotResponse: {
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
            /** Ends */
            ends: string | null;
            /** Found */
            found: boolean;
            /**
             * Recurring
             * @default false
             */
            recurring: boolean;
            /** Starts */
            starts: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Web Link */
            web_link: string | null;
        };
        /** FieldChangeResponse */
        FieldChangeResponse: {
            /**
             * Added
             * @default []
             */
            added: string[];
            /** After */
            after: string | null;
            after_time: components["schemas"]["RecordedTimeResponse"] | null;
            /** Before */
            before: string | null;
            before_time: components["schemas"]["RecordedTimeResponse"] | null;
            /** Field */
            field: string;
            /**
             * Removed
             * @default []
             */
            removed: string[];
        };
        /** GoogleAccountAccessResponse */
        GoogleAccountAccessResponse: {
            /** Calendar Api */
            calendar_api: boolean;
            /** Calendar List Access */
            calendar_list_access: boolean;
            /** Calendars Visible */
            calendars_visible: number;
            /** Event Access */
            event_access: boolean;
            /** Writable Calendars */
            writable_calendars: number;
        };
        /** GoogleConfigurationResponse */
        GoogleConfigurationResponse: {
            /** Configured */
            configured: boolean;
            /** Redirect Uri */
            redirect_uri: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentResponse */
        IncidentResponse: {
            /** Account Id */
            account_id: string | null;
            /** Category */
            category: string;
            /** Id */
            id: string;
            /** Opened At */
            opened_at: string;
            /** Resolution */
            resolution: ("sync_succeeded" | "blocks_cleared" | "rule_removed") | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Rule Id */
            rule_id: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "open" | "resolved";
            /** Summary */
            summary: string;
            /** Updated At */
            updated_at: string;
        };
        /** LogUsageResponse */
        LogUsageResponse: {
            /** Bytes */
            bytes: number;
            /** Files */
            files: number;
            /** Newest At */
            newest_at: string | null;
            /** Oldest At */
            oldest_at: string | null;
        };
        /** NamedCalendarEndpointResponse */
        NamedCalendarEndpointResponse: {
            /** Calendar Id */
            calendar_id: string;
            /** Calendar Name */
            calendar_name: string | null;
            /** Connected Account Id */
            connected_account_id: string;
        };
        /** PasswordRequest */
        PasswordRequest: {
            /** Password */
            password: string;
        };
        /** PreviewItemResponse */
        PreviewItemResponse: {
            /** All Day */
            all_day: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "single" | "series" | "occurrence";
            /**
             * Planned Action
             * @enum {string}
             */
            planned_action: "create" | "update" | "delete" | "ignore" | "conflict";
            /** Projected Title */
            projected_title: string;
            /** Source Event Id */
            source_event_id: string;
        };
        /** PreviewSummaryResponse */
        PreviewSummaryResponse: {
            /** Completed At */
            completed_at: string;
            /** Eligible Events */
            eligible_events: number;
            /** Excluded Events */
            excluded_events: number;
            /** Occurrence Changes */
            occurrence_changes: number;
            /** Recurring Series */
            recurring_series: number;
        };
        /**
         * RecentChangeResponse
         * @description One written event; an identical repair repeated among recent entries is counted on it.
         */
        RecentChangeResponse: {
            entry: components["schemas"]["AuditEntryResponse"];
            /** First Occurred At */
            first_occurred_at: string;
            /** Repeats */
            repeats: number;
        };
        /** ReconcileResultResponse */
        ReconcileResultResponse: {
            /** Checked Mappings */
            checked_mappings: number;
            /** Conflicts */
            conflicts: number;
            /** Consistent */
            consistent: boolean;
            /** Created */
            created: number;
            /** Deleted */
            deleted: number;
            /** Drift */
            drift: components["schemas"]["DriftResponse"][];
            /** Ignored */
            ignored: number;
            /** Reconciliation Conflicts */
            reconciliation_conflicts: components["schemas"]["ReconciliationConflictResponse"][];
            /** Rule Id */
            rule_id: string;
            /** Updated */
            updated: number;
        };
        /** ReconciliationConflictResponse */
        ReconciliationConflictResponse: {
            /** Detail */
            detail: string;
            /** Reason */
            reason: string;
        };
        /**
         * RecordedEventResponse
         * @description The source event as its run recorded it; see ADR 0014.
         */
        RecordedEventResponse: {
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /**
             * Cancelled
             * @default false
             */
            cancelled: boolean;
            /** Ends */
            ends: string | null;
            moved_from: components["schemas"]["RecordedTimeResponse"] | null;
            /**
             * Recurring
             * @default false
             */
            recurring: boolean;
            /** Renamed From */
            renamed_from: string | null;
            /** Starts */
            starts: string | null;
            /** Title */
            title: string;
        };
        /** RecordedTimeResponse */
        RecordedTimeResponse: {
            /**
             * All Day
             * @default false
             */
            all_day: boolean;
            /** Ends */
            ends: string | null;
            /** Starts */
            starts: string | null;
        };
        /** RemovalResponse */
        RemovalResponse: {
            /** Conflicts */
            conflicts: number;
            /** Deleted */
            deleted: number;
            /** Detached */
            detached: number;
        };
        /** ReplaceRuleRequest */
        ReplaceRuleRequest: {
            destination: components["schemas"]["CalendarEndpointPayload"];
            /**
             * Projections
             * @enum {string}
             */
            projections: "delete" | "detach";
            source: components["schemas"]["CalendarEndpointPayload"];
        };
        /** RuleDetailResponse */
        RuleDetailResponse: {
            destination: components["schemas"]["NamedCalendarEndpointResponse"];
            /** Id */
            id: string;
            /** Initial Lookback Days */
            initial_lookback_days: number;
            last_reconciliation: components["schemas"]["RunOutcomeResponse"] | null;
            last_sync: components["schemas"]["RunOutcomeResponse"] | null;
            latest_preview: components["schemas"]["PreviewSummaryResponse"] | null;
            /** Mapping Count */
            mapping_count: number;
            /**
             * Privacy Policy
             * @enum {string}
             */
            privacy_policy: "busy_only" | "copy_details";
            /** Reprojection Required */
            reprojection_required: boolean;
            running: components["schemas"]["RuleWorkResponse"] | null;
            source: components["schemas"]["NamedCalendarEndpointResponse"];
            /** State */
            state: string;
            /** Sync All Day Events */
            sync_all_day_events: boolean;
            /**
             * Tentative Events
             * @enum {string}
             */
            tentative_events: "sync" | "mark" | "skip";
            /**
             * Unanswered Invitations
             * @enum {string}
             */
            unanswered_invitations: "wait" | "as_tentative";
        };
        /** RulePreviewResponse */
        RulePreviewResponse: {
            /** Eligible Events */
            eligible_events: number;
            /** Excluded Events */
            excluded_events: number;
            /** Occurrence Changes */
            occurrence_changes: number;
            /** Recurring Series */
            recurring_series: number;
            /** Rule Id */
            rule_id: string;
            /** Sample */
            sample: components["schemas"]["PreviewItemResponse"][];
        };
        /** RuleReplacementResponse */
        RuleReplacementResponse: {
            /** Conflicts */
            conflicts: number;
            /** Deleted */
            deleted: number;
            /** Detached */
            detached: number;
            rule: components["schemas"]["RuleResponse"];
        };
        /** RuleResponse */
        RuleResponse: {
            destination: components["schemas"]["CalendarEndpointPayload"];
            /** Id */
            id: string;
            /**
             * Privacy Policy
             * @enum {string}
             */
            privacy_policy: "busy_only" | "copy_details";
            /** Reprojection Required */
            reprojection_required: boolean;
            source: components["schemas"]["CalendarEndpointPayload"];
            /** State */
            state: string;
            /** Sync All Day Events */
            sync_all_day_events: boolean;
            /**
             * Tentative Events
             * @enum {string}
             */
            tentative_events: "sync" | "mark" | "skip";
            /**
             * Unanswered Invitations
             * @enum {string}
             */
            unanswered_invitations: "wait" | "as_tentative";
        };
        /** RuleSummaryResponse */
        RuleSummaryResponse: {
            destination: components["schemas"]["NamedCalendarEndpointResponse"];
            /** Id */
            id: string;
            last_sync: components["schemas"]["RunOutcomeResponse"] | null;
            latest_preview: components["schemas"]["PreviewSummaryResponse"] | null;
            /**
             * Privacy Policy
             * @enum {string}
             */
            privacy_policy: "busy_only" | "copy_details";
            /** Reprojection Required */
            reprojection_required: boolean;
            running: components["schemas"]["RuleWorkResponse"] | null;
            source: components["schemas"]["NamedCalendarEndpointResponse"];
            /** State */
            state: string;
            /** Sync All Day Events */
            sync_all_day_events: boolean;
            /**
             * Tentative Events
             * @enum {string}
             */
            tentative_events: "sync" | "mark" | "skip";
            /**
             * Unanswered Invitations
             * @enum {string}
             */
            unanswered_invitations: "wait" | "as_tentative";
        };
        /** RuleWorkResponse */
        RuleWorkResponse: {
            /** Done */
            done: number;
            /** Handling */
            handling: ("delete" | "detach") | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "preview" | "sync" | "reconciliation" | "removal";
            /** Stage */
            stage: ("preview" | "sync" | "reconciliation" | "removal") | null;
            /** Started At */
            started_at: string;
            /** Total */
            total: number | null;
        };
        /** RunOutcomeResponse */
        RunOutcomeResponse: {
            /** Checked Mappings */
            checked_mappings: number;
            /** Completed At */
            completed_at: string;
            /** Conflicts */
            conflicts: number;
            /** Created */
            created: number;
            /** Deleted */
            deleted: number;
            /** Drift */
            drift: number;
            /** Failure Kind */
            failure_kind: string | null;
            /** Full Run */
            full_run: boolean;
            /** Last Succeeded At */
            last_succeeded_at: string | null;
            /** Succeeded */
            succeeded: boolean;
            /** Updated */
            updated: number;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** SetupStatusResponse */
        SetupStatusResponse: {
            /** Administrator Configured */
            administrator_configured: boolean;
        };
        /**
         * SourceChangeResponse
         * @description What changed in the entry's source event; values are kept for 90 days.
         */
        SourceChangeResponse: {
            /** Changes */
            changes: components["schemas"]["FieldChangeResponse"][];
            /** Fields */
            fields: string[];
            /** Values Available */
            values_available: boolean;
        };
        /** StorageResponse */
        StorageResponse: {
            /** Activity Ages */
            activity_ages: number[];
            database: components["schemas"]["DatabaseUsageResponse"];
            logs: components["schemas"]["LogUsageResponse"] | null;
        };
        /** SyncResultResponse */
        SyncResultResponse: {
            /** Conflicts */
            conflicts: number;
            /** Created */
            created: number;
            /** Deleted */
            deleted: number;
            /** Ignored */
            ignored: number;
            /** Rule Id */
            rule_id: string;
            /** Updated */
            updated: number;
        };
        /** UpdateRulePolicyRequest */
        UpdateRulePolicyRequest: {
            /**
             * Privacy Policy
             * @enum {string}
             */
            privacy_policy: "busy_only" | "copy_details";
            /** Sync All Day Events */
            sync_all_day_events: boolean;
            /**
             * Tentative Events
             * @enum {string}
             */
            tentative_events: "sync" | "mark" | "skip";
            /**
             * Unanswered Invitations
             * @enum {string}
             */
            unanswered_invitations: "wait" | "as_tentative";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedAccountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_v1_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_calendars_api_v1_accounts__account_id__calendars_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredCalendarResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_account_api_v1_accounts__account_id__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedAccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_account_access_api_v1_accounts__account_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAccountAccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_api_v1_audit_entries_get: {
        parameters: {
            query?: {
                rule_id?: string | null;
                category?: ("changed" | "unchanged" | "skipped" | "blocked")[] | null;
                before?: number | null;
                limit?: number;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_entry_api_v1_audit_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_entry_changes_api_v1_audit_entries__entry_id__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceChangeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_activity_event_api_v1_audit_entries__entry_id__event_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_configuration_api_v1_google_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleConfigurationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_google_oauth_api_v1_oauth_google_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_changes_api_v1_recent_changes_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecentChangeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rule_details_api_v1_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_rule_api_v1_rules__rule_id__delete: {
        parameters: {
            query: {
                projections: "delete" | "detach";
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_rule_policy_api_v1_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRulePolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_rule_api_v1_rules__rule_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_rule_api_v1_rules__rule_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_rule_api_v1_rules__rule_id__preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_now_api_v1_rules__rule_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_rule_calendars_api_v1_rules__rule_id__replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReplacementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_now_api_v1_rules__rule_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_status_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_in_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_out_api_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_status_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    create_admin_api_v1_setup_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    storage_usage_api_v1_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clearable_activity_api_v1_storage_activity_get: {
        parameters: {
            query: {
                older_than_days: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearableActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_activity_api_v1_storage_activity_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearActivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearedActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_logs_api_v1_storage_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_logs_api_v1_storage_logs_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                calendar_sync_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
